/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationEditorDialog: typeof import('./components/resource-editors/ApplicationEditorDialog.vue')['default']
    CallRelationsEditor: typeof import('./components/CallRelationsEditor.vue')['default']
    ContactAvatar: typeof import('./components/contact/ContactAvatar.vue')['default']
    ContactCard: typeof import('./components/contact/ContactCard.vue')['default']
    CopyableTextCell: typeof import('./components/table/CopyableTextCell.vue')['default']
    DashboardKpiGrid: typeof import('./components/dashboard/DashboardKpiGrid.vue')['default']
    DashboardOverviewPanels: typeof import('./components/dashboard/DashboardOverviewPanels.vue')['default']
    DashboardQuickHub: typeof import('./components/dashboard/DashboardQuickHub.vue')['default']
    DashboardRecentChanges: typeof import('./components/dashboard/DashboardRecentChanges.vue')['default']
    DeploymentPanel: typeof import('./components/DeploymentPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ErrorDetailDialog: typeof import('./components/ErrorDetailDialog.vue')['default']
    MiddlewareEditorDialog: typeof import('./components/resource-editors/MiddlewareEditorDialog.vue')['default']
    NginxConfigEditorDialog: typeof import('./components/resource-editors/NginxConfigEditorDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchToolbar: typeof import('./components/filters/SearchToolbar.vue')['default']
    TopologyCanvas: typeof import('./components/topology/TopologyCanvas.vue')['default']
    TopologyControlBar: typeof import('./components/topology/TopologyControlBar.vue')['default']
    TopologyDetailPanel: typeof import('./components/topology/TopologyDetailPanel.vue')['default']
    TopologyLegend: typeof import('./components/topology/TopologyLegend.vue')['default']
    TopologyToolbar: typeof import('./components/topology/TopologyToolbar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
